name: CD

on:
  - push

jobs:
  build_and_deploy:
    name: Deploy Container to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./container/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/vanilla/container:${{ github.sha }}

