name: Dog Food
on:
  push:
    branches:
      - dogfood/*
jobs:
  build:
    name: Dogfooding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: nexforum@${{ secrets.NEXFORUM_DEV_SERVER }}
          privateKey: ${{ secrets.SSH_KEY_OF_NEXFORUM }}
          command: |
            sudo su
            cd /home/nexforum/vanilla-project/vanilla
            git pull
            composer install
